import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
        <Link
            href="/"
            className={styles.card}
          >
            <h2>
              Home <span>-&gt;</span>
            </h2>
          </Link>
          <Link
            href="/contacts"
            className={styles.card}
          >
            <h2>
              Contacts <span>-&gt;</span>
            </h2>
          </Link>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="/learn/react"
            className={styles.card}
          >
            <h2 className={inter.className}>
              Learn ReactJS <span>-&gt;</span>
            </h2>
          </a>

          <Link
            href="/learn/next"
            className={styles.card}
            // target="_blank" ==> causes the opening of a new tab
          >
            <h2 className={inter.className}>
              Learn NextJS <span>-&gt;</span>
            </h2>
          </Link>

          <a
            href="/learn/vue"
            className={styles.card}
          >
            <h2 className={inter.className}>
              Learn VueJS <span>-&gt;</span>
            </h2>
          </a>

          <a
            href="/learn/angular"
            className={styles.card}
          >
            <h2 className={inter.className}>
              Learn AngularJS <span>-&gt;</span>
            </h2>
          </a>
        </div>
      </main>
    </>
  )
}
